#!/bin/bash

SIMUL=./runsimul
FILES=maze.lst

rm -f $FILES
find . -name "*.maz" > $FILES
find . -name "*.MAZ" >> $FILES

while read line
do
	echo $line
	$SIMUL "$line"
	rc=$?
	if [[ $rc != 0 ]]; then
		echo .
		echo "Micromouse simulation has failed!!!"
		exit
	fi
done < $FILES

rm -f $FILES

exit
